// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyMeals.Data;

namespace WeeklyMeals.Migrations
{
    [DbContext(typeof(WeeklyMealsContext))]
    [Migration("20210520021145_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeeklyMeals.Models.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroceryAisleID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.HasIndex("GroceryAisleID");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("WeeklyMeals.Models.GroceryAisle", b =>
                {
                    b.Property<int>("GroceryAisleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroceryAisleID");

                    b.ToTable("GroceryAisle");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Ingredient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<double>("PrepTypeID")
                        .HasColumnType("float");

                    b.Property<int?>("RecipeID")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<double>("SizeType")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("WeeklyMeals.Models.MealPlan", b =>
                {
                    b.Property<int>("MealPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MealPlanID");

                    b.ToTable("MealPlan");
                });

            modelBuilder.Entity("WeeklyMeals.Models.MealPlanRecipe", b =>
                {
                    b.Property<int>("MealPlanRecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MealPlanID")
                        .HasColumnType("int");

                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.HasKey("MealPlanRecipeID");

                    b.HasIndex("MealPlanID");

                    b.HasIndex("RecipeID");

                    b.ToTable("MealPlanRecipe");
                });

            modelBuilder.Entity("WeeklyMeals.Models.PrepType", b =>
                {
                    b.Property<int>("PrepTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrepTypeID");

                    b.ToTable("PrepType");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("WeeklyMeals.Models.SizeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SizeType");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Step", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Step");
                });

            modelBuilder.Entity("WeeklyMeals.Models.UserSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MealPlanSelection")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Food", b =>
                {
                    b.HasOne("WeeklyMeals.Models.GroceryAisle", "GroceryAisle")
                        .WithMany("Foods")
                        .HasForeignKey("GroceryAisleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryAisle");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Ingredient", b =>
                {
                    b.HasOne("WeeklyMeals.Models.Food", "Food")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyMeals.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeID");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("WeeklyMeals.Models.MealPlanRecipe", b =>
                {
                    b.HasOne("WeeklyMeals.Models.MealPlan", "MealPlan")
                        .WithMany("MealPlanRecipes")
                        .HasForeignKey("MealPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyMeals.Models.Recipe", "Recipe")
                        .WithMany("MealPlanRecipes")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Step", b =>
                {
                    b.HasOne("WeeklyMeals.Models.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeID");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Food", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("WeeklyMeals.Models.GroceryAisle", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("WeeklyMeals.Models.MealPlan", b =>
                {
                    b.Navigation("MealPlanRecipes");
                });

            modelBuilder.Entity("WeeklyMeals.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MealPlanRecipes");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
